### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by wooni-github** [KevinXu02/splatfacto-w#22]
Hi, I'm encountering an issue when installing `splatfacto-w` using the command `ns-install-cli`. 

I've been following the same process to set up the environment for about three weeks, It worked.
But now the same commands are giving me an error, even though I haven't changed any environment settings. 

Has anyone else experienced a similar issue?

I used these commands to install (actually, same to instruction)

```
conda create --name nerfstudio114_w1 -y python=3.8
conda activate nerfstudio114_w1
pip install --upgrade pip

pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit -y
pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .

#until now, it works. It successfully run nerfstudio (ns-train, ns-process-data and so on)

git clone https://github.com/KevinXu02/splatfacto-w
cd splatfacto-w/
pip install -e .
ns-install-cli # causes error
```

and error is : 

```
(nerfstudio114_w1) dwkim@dwkim-System-Product-Name:~/GithubProjects/nerfstudio_w1/splatfacto-w$ ns-install-cli
[16:17:05] 🔍 Detected conda environment /home/dwkim/miniconda3/envs/nerfstudio114_w1!                    install.py:363
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/bash/_ns-in               
           stall-cli!                                                                                                   
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/zsh/_ns-ins               
           tall-cli!                                                                                                    
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/zsh/_ns-dev               
           -test!                                                                                                       
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/bash/_ns-de               
           v-test!                                                                                                      
[16:17:07] ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/bash/_ns-de               
           v-sync-viser-message-defs!                                                                                   
[16:17:08] ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/zsh/_ns-dev               
           -sync-viser-message-defs!                                                                                    
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/bash/_ns-do               
           wnload-data!                                                                                                 
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/zsh/_ns-dow               
           nload-data!                                                                                                  
[16:17:10] ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/zsh/_ns-pro               
           cess-data!                                                                                                   
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/bash/_ns-pr               
           ocess-data!                                                                                                  
[16:17:13] ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/zsh/_ns-eva               
           l!                                                                                                           
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/bash/_ns-vi               
           ewer!                                                                                                        
           ❌ Completion script generation failed: ['ns-train', '--tyro-print-completion', 'bash']        install.py:123
           Traceback (most recent call last):                                                             install.py:127
             File "/home/dwkim/miniconda3/envs/nerfstudio114_w1/bin/ns-train", line 8, in <module>                      
               sys.exit(entrypoint())                                                                                   
             File "/home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/train.py", line               
           263, in entrypoint                                                                                           
               tyro.cli(                                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_cli.py", line                
           207, in cli                                                                                                  
               output = _cli_impl(                                                                                      
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_cli.py", line                
           408, in _cli_impl                                                                                            
               parser_spec = _parsers.ParserSpecification.from_callable_or_type(                                        
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 114, in from_callable_or_type                                                                           
               field_out = handle_field(                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 320, in handle_field                                                                                    
               subparsers_attempt = SubparsersSpecification.from_field(                                                 
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 526, in from_field                                                                                      
               subparser = ParserSpecification.from_callable_or_type(                                                   
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 114, in from_callable_or_type                                                                           
               field_out = handle_field(                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 345, in handle_field                                                                                    
               return ParserSpecification.from_callable_or_type(                                                        
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 114, in from_callable_or_type                                                                           
               field_out = handle_field(                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 345, in handle_field                                                                                    
               return ParserSpecification.from_callable_or_type(                                                        
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 114, in from_callable_or_type                                                                           
               field_out = handle_field(                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 320, in handle_field                                                                                    
               subparsers_attempt = SubparsersSpecification.from_field(                                                 
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 469, in from_field                                                                                      
               assert default_name is not None, (                                                                       
           AssertionError: `pipeline.datamanager.dataparser` was provided a default value of type <class                
           'splatfactow.nerfw_dataparser.NerfWDataParserConfig'> but no matching subcommand was found. A                
           type may be missing in the Union type declaration for `pipeline.datamanager.dataparser`, which               
           currently expects [typing_extensions.Annotated, typing_extensions.Annotated,                                 
           typing_extensions.Annotated, typing_extensions.Annotated, typing_extensions.Annotated,                       
           typing_extensions.Annotated, typing_extensions.Annotated, typing_extensions.Annotated,                       
           typing_extensions.Annotated, typing_extensions.Annotated, typing_extensions.Annotated,                       
           typing_extensions.Annotated, typing_extensions.Annotated, typing_extensions.Annotated,                       
           typing_extensions.Annotated]. The types may also be too complex for tyro's subcommand matcher;               
           support is particularly limited for custom generic types.                                                    
                                                                                                                        
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/bash/_ns-ev               
           al!                                                                                                          
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/zsh/_ns-vie               
           wer!                                                                                                         
           ❌ Completion script generation failed: ['ns-train', '--tyro-print-completion', 'zsh']         install.py:123
           Traceback (most recent call last):                                                             install.py:127
             File "/home/dwkim/miniconda3/envs/nerfstudio114_w1/bin/ns-train", line 8, in <module>                      
               sys.exit(entrypoint())                                                                                   
             File "/home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/train.py", line               
           263, in entrypoint                                                                                           
               tyro.cli(                                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_cli.py", line                
           207, in cli                                                                                                  
               output = _cli_impl(                                                                                      
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_cli.py", line                
           408, in _cli_impl                                                                                            
               parser_spec = _parsers.ParserSpecification.from_callable_or_type(                                        
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 114, in from_callable_or_type                                                                           
               field_out = handle_field(                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 320, in handle_field                                                                                    
               subparsers_attempt = SubparsersSpecification.from_field(                                                 
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 526, in from_field                                                                                      
               subparser = ParserSpecification.from_callable_or_type(                                                   
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 114, in from_callable_or_type                                                                           
               field_out = handle_field(                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 345, in handle_field                                                                                    
               return ParserSpecification.from_callable_or_type(                                                        
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 114, in from_callable_or_type                                                                           
               field_out = handle_field(                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 345, in handle_field                                                                                    
               return ParserSpecification.from_callable_or_type(                                                        
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 114, in from_callable_or_type                                                                           
               field_out = handle_field(                                                                                
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 320, in handle_field                                                                                    
               subparsers_attempt = SubparsersSpecification.from_field(                                                 
             File                                                                                                       
           "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_parsers.py",                 
           line 469, in from_field                                                                                      
               assert default_name is not None, (                                                                       
           AssertionError: `pipeline.datamanager.dataparser` was provided a default value of type <class                
           'splatfactow.nerfw_dataparser.NerfWDataParserConfig'> but no matching subcommand was found. A                
           type may be missing in the Union type declaration for `pipeline.datamanager.dataparser`, which               
           currently expects [typing_extensions.Annotated, typing_extensions.Annotated,                                 
           typing_extensions.Annotated, typing_extensions.Annotated, typing_extensions.Annotated,                       
           typing_extensions.Annotated, typing_extensions.Annotated, typing_extensions.Annotated,                       
           typing_extensions.Annotated, typing_extensions.Annotated, typing_extensions.Annotated,                       
           typing_extensions.Annotated, typing_extensions.Annotated, typing_extensions.Annotated,                       
           typing_extensions.Annotated]. The types may also be too complex for tyro's subcommand matcher;               
           support is particularly limited for custom generic types.                                                    
                                                                                                                        
[16:17:14] ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/bash/_ns-re               
           nder!                                                                                                        
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/zsh/_ns-ren               
           der!                                                                                                         
[16:17:17] ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/bash/_ns-ex               
           port!                                                                                                        
           ✔ Wrote new completion to                                                                      install.py:133
           /home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/zsh/_ns-exp               
           ort!                                                                                                         
Traceback (most recent call last):
  File "/home/dwkim/miniconda3/envs/nerfstudio114_w1/bin/ns-install-cli", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/install.py", line 411, in entrypoint
    tyro.cli(main, description=__doc__)
  File "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/site-packages/tyro/_cli.py", line 229, in cli
    return run_with_args_from_cli()
  File "/home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/install.py", line 392, in main
    _generate_completions_files(completions_dir, scripts_dir, shells_supported, shells_found)
  File "/home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/install.py", line 323, in _generate_completions_files
    completion_paths = list(
  File "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/install.py", line 325, in <lambda>
    lambda path_or_entrypoint_and_shell: _generate_completion(
  File "/home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/install.py", line 128, in _generate_completion
    raise e
  File "/home/dwkim/GithubProjects/nerfstudio_w1/nerfstudio/nerfstudio/scripts/completions/install.py", line 115, in _generate_completion
    new = subprocess.run(
  File "/home/dwkim/miniconda3/envs/nerfstudio114_w1/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ns-train', '--tyro-print-completion', 'zsh']' returned non-zero exit status 1.

```

**Comment by wooni-github** [comment]
Solved using [this branch](https://github.com/redefiningsurgery/splatfacto-w) with [this](https://github.com/redefiningsurgery/splatfacto-w/pull/1/files)

Envs,
- nerfstudio 1.1.5 and gsplat 1.4.0 
- `ns-trains splatfacto-w-light` works (`ns-train splatfacto-w` didn't work)
