### ISSUE TITLE
AttributeError: 'SplatfactoWDatamanager' object has no attribute 'fixed_indices_eval_dataloader'

### ISSUE THREAD

**Issue by sion3951** [KevinXu02/splatfacto-w#3]
I am running with the command ns-train splatfacto-w-light --data path/to/data nerfstudio-data

I get the error  stream:
Traceback (most recent call last):
  File "/home/sion/miniconda/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/sion/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/sion/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/sion/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/sion/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/sion/nerfstudio/nerfstudio/engine/trainer.py", line 183, in setup
    self.viewer_state = ViewerState(
  File "/home/sion/nerfstudio/nerfstudio/viewer/viewer.py", line 252, in __init__
    if len(parse_object(pipeline, LegacyViewerElement, "Custom Elements")) > 0:
  File "/home/sion/nerfstudio/nerfstudio/viewer/utils.py", line 155, in parse_object
    lower_rets = parse_object(v, type_check, new_tree_stub)
  File "/home/sion/nerfstudio/nerfstudio/viewer/utils.py", line 143, in parse_object
    obj_props = [(k, getattr(obj, k)) for k in dir(obj) if not isinstance(getattr(type(obj), k, None), cached_property)]
  File "/home/sion/nerfstudio/nerfstudio/viewer/utils.py", line 143, in <listcomp>
    obj_props = [(k, getattr(obj, k)) for k in dir(obj) if not isinstance(getattr(type(obj), k, None), cached_property)]
  File "/home/sion/miniconda/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SplatfactoWDatamanager' object has no attribute 'fixed_indices_eval_dataloader'

using the same command but with just splatfacto runs, I don't know if I am doing some thing wrong?

**Comment by KevinXu02** [comment]
Can you try pull the latest version? I pushed the latest config like 15 min ago.

**Comment by sion3951** [comment]
will pip install git+https://github.com/KevinXu02/splatfacto-w do that and replace the older version? 

I have just run that now and rerun and I get the same error.

**Comment by KevinXu02** [comment]
Oh I think I need to bump the version. Sorry for that. I will push a new version.

**Comment by sion3951** [comment]
Got it training, cant see it in the viewer for some reason?
![Screenshot from 2024-07-16 14-22-06](https://github.com/user-attachments/assets/e5219a02-37cc-4fc5-82b0-468b2ee23a7f)


I get this error:
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/sion/miniconda/envs/nerfstudio/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sion/nerfstudio/nerfstudio/viewer/render_state_machine.py", line 225, in run
    outputs = self._render_img(action.camera_state)
  File "/home/sion/nerfstudio/nerfstudio/viewer/render_state_machine.py", line 169, in _render_img
    outputs = self.viewer.get_model().get_outputs_for_camera(camera, obb_box=obb)
  File "/home/sion/miniconda/envs/nerfstudio/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

**Comment by KevinXu02** [comment]
Could you please try the viewer in this PR (https://github.com/nerfstudio-project/nerfstudio/pull/3293)? I'm not sure if the newest viewer would work.

**Comment by sion3951** [comment]
Works with that, thanks for your help!
