### ISSUE TITLE
splatfacto-w datamanager type fails assertion

### ISSUE THREAD

**Issue by j93hahn** [KevinXu02/splatfacto-w#4]
```
Traceback (most recent call last):                                                                                                         [53/1849]
  File "/conda_tmp/mc3/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 298, in train
    self.eval_iteration(step)
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/utils/decorators.py", line 70, in wrapper
    ret = func(self, *args, **kwargs)
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 559, in eval_iteration
    metrics_dict = self.pipeline.get_average_eval_image_metrics(step=step)
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/conda_tmp/mc3/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 428, in get_average_eval_image_metrics
    assert isinstance(self.datamanager, (VanillaDataManager, ParallelDataManager, FullImageDatamanager))
AssertionError
```

I get this traceback currently. I have `nerfstudio==1.1.3` and `splatfacto==0.1.1` installed. For splatfacto, I used the `pip install -e .` command, while I just used `pip install nerfstudio`. Has this problem been addressed previously? I imagine I just have a wrong library version, and would prefer not to go through the effort of looking through the entire nerfstudio codebase to fix this one assertion

Here is my `pip list` output:
```
(base) Apptainer> pip list
Package                   Version        Editable project location
------------------------- -------------- ------------------------------------
absl-py                   2.1.0
addict                    2.4.0
anaconda-anon-usage       0.4.4
anyio                     4.4.0
appdirs                   1.4.4
archspec                  0.2.3
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.2.0
av                        12.3.0
awscli                    1.33.28
Babel                     2.15.0
backcall                  0.2.0
beautifulsoup4            4.12.3
bidict                    0.23.1
bleach                    6.1.0
blinker                   1.8.2
boltons                   23.0.0
botocore                  1.34.146
Brotli                    1.0.9
cachetools                5.4.0
certifi                   2024.7.4
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        2.0.4
click                     8.1.7
colorama                  0.4.6
colorlog                  6.8.2
comet-ml                  3.44.1
comm                      0.2.2
conda                     23.9.0
conda-content-trust       0.2.0
conda-libmamba-solver     23.9.3
conda-package-handling    2.3.0
conda_package_streaming   0.10.0
ConfigArgParse            1.7
configobj                 5.0.8
contourpy                 1.1.1
cryptography              43.0.0
cycler                    0.12.1
dash                      2.17.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
debugpy                   1.8.2
decorator                 5.1.1
defusedxml                0.7.1
descartes                 1.1.0
dill                      0.3.8
distro                    1.9.0
docker-pycreds            0.4.0
docstring_parser          0.16
docutils                  0.16
dulwich                   0.22.1
embreex                   2.17.7.post5
eval_type_backport        0.2.0
everett                   3.1.0
exceptiongroup            1.2.2
executing                 2.0.1
fastjsonschema            2.20.0
filelock                  3.15.4
fire                      0.6.0
Flask                     3.0.3
fonttools                 4.53.1
fpsample                  0.3.2
fqdn                      1.5.1
frozendict                2.4.2
fsspec                    2024.6.1
gdown                     5.2.0
gitdb                     4.0.11
GitPython                 3.1.43
google-auth               2.32.0
google-auth-oauthlib      1.0.0
grpcio                    1.65.1
gsplat                    1.0.0
h11                       0.14.0
h5py                      3.11.0
httpcore                  1.0.5
httpx                     0.27.0
idna                      3.7
imageio                   2.34.2
importlib_metadata        8.0.0
importlib_resources       6.4.0
ipykernel                 6.29.5
ipython                   8.12.3
ipywidgets                8.1.3
isoduration               20.11.0
itsdangerous              2.2.0
jaxtyping                 0.2.19
jedi                      0.19.1
Jinja2                    3.1.4
jmespath                  1.0.1
joblib                    1.4.2
json5                     0.9.25
jsonpatch                 1.33
jsonpointer               2.1
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter                   1.0.0
jupyter_client            8.6.2
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.2
jupyter_server_terminals  0.5.3
jupyterlab                4.2.4
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
jupyterlab_widgets        3.0.11
kiwisolver                1.4.5
lazy_loader               0.4
libmambapy                1.5.1
lightning-utilities       0.11.5
lxml                      5.2.2
manifold3d                2.5.1
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.7.5
matplotlib-inline         0.1.7
mdurl                     0.1.2
mediapy                   1.2.2
menuinst                  2.1.1
mistune                   3.0.2
mpmath                    1.3.0
msgpack                   1.0.8
msgpack-numpy             0.4.8
multiprocess              0.70.16
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nerfacc                   0.5.2
nerfstudio                1.1.3
nest-asyncio              1.6.0
networkx                  3.1
ninja                     1.11.1.1
nodeenv                   1.9.1
notebook                  7.2.1
notebook_shim             0.2.4
numpy                     1.24.4
nuscenes-devkit           1.1.9
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.5.82
nvidia-nvtx-cu12          12.1.105
oauthlib                  3.2.2
open3d                    0.18.0
opencv-python             4.8.0.76
overrides                 7.7.0
packaging                 24.1
pandas                    2.0.3
pandocfilters             1.5.1
parso                     0.8.4
pathos                    0.3.2
pexpect                   4.9.0
pickleshare               0.7.5
pillow                    10.4.0
pip                       24.1.2
pkgutil_resolve_name      1.3.10
platformdirs              3.10.0
plotly                    5.22.0
pluggy                    1.0.0
pox                       0.3.4
ppft                      1.7.6.8
prometheus_client         0.20.0
prompt_toolkit            3.0.47
protobuf                  3.20.3
psutil                    6.0.0
ptyprocess                0.7.0
pure_eval                 0.2.3
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pycocotools               2.0.7
pycollada                 0.8
pycosat                   0.6.6
pycparser                 2.22
Pygments                  2.18.0
pyliblzfse                0.4.1
pymeshlab                 2023.12.post1
pyngrok                   7.2.0
pyOpenSSL                 24.2.1
pyparsing                 3.1.2
pyquaternion              0.9.9
PySocks                   1.7.1
python-box                6.1.0
python-dateutil           2.9.0.post0
python-engineio           4.9.1
python-json-logger        2.0.7
python-socketio           5.11.3
pytorch-msssim            1.0.0
pytz                      2024.1
PyWavelets                1.4.1
PyYAML                    6.0.1
pyzmq                     26.0.3
qtconsole                 5.5.2
QtPy                      2.4.1
rawpy                     0.21.0
referencing               0.35.1
requests                  2.32.3
requests-oauthlib         2.0.0
requests-toolbelt         1.0.0
retrying                  1.3.4
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.7.1
rpds-py                   0.19.0
rsa                       4.7.2
Rtree                     1.3.0
ruamel.yaml               0.17.21
ruamel.yaml.clib          0.2.6
s3transfer                0.10.2
scikit-image              0.21.0
scikit-learn              1.3.2
scipy                     1.10.1
semantic-version          2.10.0
Send2Trash                1.8.3
sentry-sdk                2.10.0
setproctitle              1.3.3
setuptools                69.5.1
shapely                   2.0.5
shtab                     1.7.1
simple-websocket          1.0.0
simplejson                3.19.2
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
soupsieve                 2.5
splatfacto-w              0.1.1          /share/data/2pals/jjahn/splatfacto-w
splines                   0.3.0
stack-data                0.6.3
svg.path                  6.3
sympy                     1.13.1
tenacity                  8.5.0
tensorboard               2.14.0
tensorboard-data-server   0.7.2
termcolor                 2.4.0
terminado                 0.18.1
threadpoolctl             3.5.0
tifffile                  2023.7.10
timm                      0.6.7
tinycss2                  1.3.0
tinycudann                1.7
tomli                     2.0.1
torch                     2.3.1+cu121
torch-fidelity            0.3.0
torchmetrics              1.4.0.post0
torchvision               0.18.1+cu121
tornado                   6.4.1
tqdm                      4.66.4
traitlets                 5.14.3
trimesh                   4.4.3
triton                    2.3.1
typeguard                 4.3.0
types-python-dateutil     2.9.0.20240316
typing_extensions         4.12.2
tyro                      0.8.5
tzdata                    2024.1
uri-template              1.3.0
urllib3                   1.26.19
vhacdx                    0.0.8.post1
viser                     0.1.27
wandb                     0.17.5
wcwidth                   0.2.13
webcolors                 24.6.0
webencodings              0.5.1
websocket-client          1.8.0
websockets                12.0
Werkzeug                  3.0.3
wheel                     0.43.0
widgetsnbextension        4.0.11
wrapt                     1.16.0
wsproto                   1.2.0
wurlitzer                 3.1.1
xatlas                    0.0.9
xxhash                    3.4.1
yourdfpy                  0.0.56
zipp                      3.19.2
zstandard                 0.22.0
```

**Comment by j93hahn** [comment]
And the command I used is: `ns-train splatfacto-w --data data/brandenburg-gate --vis wandb`

**Comment by KevinXu02** [comment]
Hi. Can you try update to the latest dev version of nerfstudio (clone and from source)? I made a pr for this and it should have been merged. Or you can comment that line.

**Comment by j93hahn** [comment]
What's the command for updating to the latest dev version of nerfstudio?

**Comment by KevinXu02** [comment]
```
git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .
```

**Comment by j93hahn** [comment]
`Successfully installed nerfstudio-1.1.3 opencv-python-4.10.0.84 viser-0.2.3`

is this what I should be getting?

**Comment by j93hahn** [comment]
Now I get another issue:

```
(base) Apptainer> ns-install-cli
Traceback (most recent call last):
  File "/conda_tmp/mc3/bin/ns-install-cli", line 5, in <module>
    from nerfstudio.scripts.completions.install import entrypoint
ModuleNotFoundError: No module named 'nerfstudio.scripts.completions.install'
```
